//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsVpcPeeringMirror) DeepCopyInto(out *AwsVpcPeeringMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsVpcPeeringMirror.
func (in *AwsVpcPeeringMirror) DeepCopy() *AwsVpcPeeringMirror {
	if in == nil {
		return nil
	}
	out := new(AwsVpcPeeringMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsVpcPeeringMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsVpcPeeringMirrorList) DeepCopyInto(out *AwsVpcPeeringMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AwsVpcPeeringMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsVpcPeeringMirrorList.
func (in *AwsVpcPeeringMirrorList) DeepCopy() *AwsVpcPeeringMirrorList {
	if in == nil {
		return nil
	}
	out := new(AwsVpcPeeringMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsVpcPeeringMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsVpcPeeringMirrorSpec) DeepCopyInto(out *AwsVpcPeeringMirrorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsVpcPeeringMirrorSpec.
func (in *AwsVpcPeeringMirrorSpec) DeepCopy() *AwsVpcPeeringMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(AwsVpcPeeringMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsVpcPeeringMirrorStatus) DeepCopyInto(out *AwsVpcPeeringMirrorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsVpcPeeringMirrorStatus.
func (in *AwsVpcPeeringMirrorStatus) DeepCopy() *AwsVpcPeeringMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(AwsVpcPeeringMirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVpcPeeringMirror) DeepCopyInto(out *AzureVpcPeeringMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVpcPeeringMirror.
func (in *AzureVpcPeeringMirror) DeepCopy() *AzureVpcPeeringMirror {
	if in == nil {
		return nil
	}
	out := new(AzureVpcPeeringMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVpcPeeringMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVpcPeeringMirrorList) DeepCopyInto(out *AzureVpcPeeringMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzureVpcPeeringMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVpcPeeringMirrorList.
func (in *AzureVpcPeeringMirrorList) DeepCopy() *AzureVpcPeeringMirrorList {
	if in == nil {
		return nil
	}
	out := new(AzureVpcPeeringMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzureVpcPeeringMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVpcPeeringMirrorSpec) DeepCopyInto(out *AzureVpcPeeringMirrorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVpcPeeringMirrorSpec.
func (in *AzureVpcPeeringMirrorSpec) DeepCopy() *AzureVpcPeeringMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(AzureVpcPeeringMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureVpcPeeringMirrorStatus) DeepCopyInto(out *AzureVpcPeeringMirrorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureVpcPeeringMirrorStatus.
func (in *AzureVpcPeeringMirrorStatus) DeepCopy() *AzureVpcPeeringMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(AzureVpcPeeringMirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpVpcPeeringMirror) DeepCopyInto(out *GcpVpcPeeringMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpVpcPeeringMirror.
func (in *GcpVpcPeeringMirror) DeepCopy() *GcpVpcPeeringMirror {
	if in == nil {
		return nil
	}
	out := new(GcpVpcPeeringMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GcpVpcPeeringMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpVpcPeeringMirrorList) DeepCopyInto(out *GcpVpcPeeringMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GcpVpcPeeringMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpVpcPeeringMirrorList.
func (in *GcpVpcPeeringMirrorList) DeepCopy() *GcpVpcPeeringMirrorList {
	if in == nil {
		return nil
	}
	out := new(GcpVpcPeeringMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GcpVpcPeeringMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpVpcPeeringMirrorSpec) DeepCopyInto(out *GcpVpcPeeringMirrorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpVpcPeeringMirrorSpec.
func (in *GcpVpcPeeringMirrorSpec) DeepCopy() *GcpVpcPeeringMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(GcpVpcPeeringMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpVpcPeeringMirrorStatus) DeepCopyInto(out *GcpVpcPeeringMirrorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpVpcPeeringMirrorStatus.
func (in *GcpVpcPeeringMirrorStatus) DeepCopy() *GcpVpcPeeringMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(GcpVpcPeeringMirrorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfsVolumeMirror) DeepCopyInto(out *NfsVolumeMirror) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfsVolumeMirror.
func (in *NfsVolumeMirror) DeepCopy() *NfsVolumeMirror {
	if in == nil {
		return nil
	}
	out := new(NfsVolumeMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NfsVolumeMirror) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfsVolumeMirrorList) DeepCopyInto(out *NfsVolumeMirrorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NfsVolumeMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfsVolumeMirrorList.
func (in *NfsVolumeMirrorList) DeepCopy() *NfsVolumeMirrorList {
	if in == nil {
		return nil
	}
	out := new(NfsVolumeMirrorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NfsVolumeMirrorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfsVolumeMirrorSpec) DeepCopyInto(out *NfsVolumeMirrorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfsVolumeMirrorSpec.
func (in *NfsVolumeMirrorSpec) DeepCopy() *NfsVolumeMirrorSpec {
	if in == nil {
		return nil
	}
	out := new(NfsVolumeMirrorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfsVolumeMirrorStatus) DeepCopyInto(out *NfsVolumeMirrorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfsVolumeMirrorStatus.
func (in *NfsVolumeMirrorStatus) DeepCopy() *NfsVolumeMirrorStatus {
	if in == nil {
		return nil
	}
	out := new(NfsVolumeMirrorStatus)
	in.DeepCopyInto(out)
	return out
}
