name: Sync Security
on:
  workflow_dispatch:

env:
  OWNER: kyma-project
  PROJECT_ID: 55
  REPO_NAME: cloud-manager-tests

permissions:
  repository-projects: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_DEBUG: "1"
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: List project items
        shell: bash
        run: |
          QUERY=$(cat .graphql/listRepoProjectItemsWithFields.graphql)
          gh api graphql -F "owner=$OWNER" -F "name=$REPO_NAME" -f "query=$QUERY"
