name: Sync Security
on:
  workflow_dispatch:

env:
  OWNER: kyma-project
  PROJECT_NUMBER: 55
  REPO_NAME: cloud-manager-tests
  GH_REPO: kyma-project/cloud-manager-tests

permissions:
  repository-projects: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GH_DEBUG: "1"
      GH_TOKEN: ${{ secrets.PROJECT_PAT }}
    steps:
      - uses: actions/checkout@v4

      - name: List project items with graphQL
        shell: bash
        run: |
          QUERY=$(cat .graphql/listRepoProjectItemsWithFields.graphql)
          gh api graphql -F "owner=$OWNER" -F "name=$REPO_NAME" -F "projectNumber=$PROJECT_NUMBER" -f "query=$QUERY"

      - name: List project items with cli
        shell: bash
        if: ${{ !cancelled() }}
        run: |
          echo "gh project item-list $PROJECT_NUMBER --owner $OWNER --format json"
          gh project item-list "$PROJECT_NUMBER" --format json
