name: Sync Security
on:
  workflow_dispatch:

env:
  APP_ID: "1228"

permissions:
  repository-projects: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print github.com api url
        shell: bash
        run: |
          echo "${{ github.api_url }}"

      - name: List github.com project items with graphQL
        shell: bash
        env:
          GH_DEBUG: "1"
          GH_TOKEN: ${{ secrets.PROJECT_PAT }}
        run: |
          QUERY=$(cat .graphql/listRepoProjectItemsWithFields.graphql)
          gh api graphql -F owner='kyma-project' -F name='cloud-manager-tests' -F projectNumber=55 --paginate --slurp -f "query=$QUERY" -f "query=$QUERY" > items.json
          jq . items.json

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "1228"
          private-key: ${{ secrets.ISSUE_READER_KEY }}
          owner: kyma
          repositories: security-scans-modular
          github-api-url: https://github.tools.sap/api/v3

      - name: List github.tools issues
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          GH_DEBUG: "1"
          GH_HOST: github.tools.sap
          GH_REPO: kyma/security-scans-modular
        run: |
          echo "Login"
          gh auth login -p https --skip-ssh-key --with-token <<< "$GH_TOKEN"

          echo "Auth status"
          gh auth status || true

          echo "Issue list"
          gh issue list \
            -R kyma/security-scans-modular \
            -S 'is:open is:issue archived:false label:team/phoenix' \
            --json id,title,url,labels \
            -L 10000 \
            > issues.json

          echo "Cat"
          jq . issues.json

      - name: Sync project items
        uses: ./.github/actions/sync-security
        with:
          issues: